# **Import Requirements**

In [7]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import kagglehub
from kagglehub import KaggleDatasetAdapter

# **Data Acquisition**

In [8]:
data = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "arjunbhasin2013/ccdata",
  "CC GENERAL.csv",
  )

C:\Users\nagar\AppData\Local\Temp\ipykernel_8228\2736278718.py:1: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  data = kagglehub.load_dataset(

In [9]:
print("Jumlah baris = ",data.shape[0])
print("Jumlah kolom = ",data.shape[1])

Jumlah baris =  8950
Jumlah kolom =  18

In [10]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 8950 entries, 0 to 8949
Data columns (total 18 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   CUST_ID                           8950 non-null   str
 1   BALANCE                           8950 non-null   float64
 2   BALANCE_FREQUENCY                 8950 non-null   float64
 3   PURCHASES                         8950 non-null   float64
 4   ONEOFF_PURCHASES                  8950 non-null   float64
 5   INSTALLMENTS_PURCHASES            8950 non-null   float64
 6   CASH_ADVANCE                      8950 non-null   float64
 7   PURCHASES_FREQUENCY               8950 non-null   float64
 8   ONEOFF_PURCHASES_FREQUENCY        8950 non-null   float64
 9   PURCHASES_INSTALLMENTS_FREQUENCY  8950 non-null   float64
 10  CASH_ADVANCE_FREQUENCY            8950 non-null   float64
 11  CASH_ADVANCE_TRX                  8950 non-null   int64
 12  PURCHASES_TRX                     8950 non-null   int64
 13  CREDIT_LIMIT                      8949 non-null   float64
 14  PAYMENTS                          8950 non-null   float64
 15  MINIMUM_PAYMENTS                  8637 non-null   float64
 16  PRC_FULL_PAYMENT                  8950 non-null   float64
 17  TENURE                            8950 non-null   int64
dtypes: float64(14), int64(3), str(1)
memory usage: 1.2 MB

In [11]:
data.columns = data.columns.str.lower()
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 8950 entries, 0 to 8949
Data columns (total 18 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   cust_id                           8950 non-null   str
 1   balance                           8950 non-null   float64
 2   balance_frequency                 8950 non-null   float64
 3   purchases                         8950 non-null   float64
 4   oneoff_purchases                  8950 non-null   float64
 5   installments_purchases            8950 non-null   float64
 6   cash_advance                      8950 non-null   float64
 7   purchases_frequency               8950 non-null   float64
 8   oneoff_purchases_frequency        8950 non-null   float64
 9   purchases_installments_frequency  8950 non-null   float64
 10  cash_advance_frequency            8950 non-null   float64
 11  cash_advance_trx                  8950 non-null   int64
 12  purchases_trx                     8950 non-null   int64
 13  credit_limit                      8949 non-null   float64
 14  payments                          8950 non-null   float64
 15  minimum_payments                  8637 non-null   float64
 16  prc_full_payment                  8950 non-null   float64
 17  tenure                            8950 non-null   int64
dtypes: float64(14), int64(3), str(1)
memory usage: 1.2 MB

In [12]:
data.describe()

,balance,balance_frequency,purchases,oneoff_purchases,installments_purchases,cash_advance,purchases_frequency,oneoff_purchases_frequency,purchases_installments_frequency,cash_advance_frequency,cash_advance_trx,purchases_trx,credit_limit,payments,minimum_payments,prc_full_payment,tenure
count,8950.000000,8950.000000,8950.000000,8950.000000,8950.000000,8950.000000,8950.000000,8950.000000,8950.000000,8950.000000,8950.000000,8950.000000,8949.000000,8950.000000,8637.000000,8950.000000,8950.000000
mean,1564.474828,0.877271,1003.204834,592.437371,411.067645,978.871112,0.490351,0.202458,0.364437,0.135144,3.248827,14.709832,4494.449450,1733.143852,864.206542,0.153715,11.517318
std,2081.531879,0.236904,2136.634782,1659.887917,904.338115,2097.163877,0.401371,0.298336,0.397448,0.200121,6.824647,24.857649,3638.815725,2895.063757,2372.446607,0.292499,1.338331
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,50.000000,0.000000,0.019163,0.000000,6.000000
25%,128.281915,0.888889,39.635000,0.000000,0.000000,0.000000,0.083333,0.000000,0.000000,0.000000,0.000000,1.000000,1600.000000,383.276166,169.123707,0.000000,12.000000
50%,873.385231,1.000000,361.280000,38.000000,89.000000,0.000000,0.500000,0.083333,0.166667,0.000000,0.000000,7.000000,3000.000000,856.901546,312.343947,0.000000,12.000000
75%,2054.140036,1.000000,1110.130000,577.405000,468.637500,1113.821139,0.916667,0.300000,0.750000,0.222222,4.000000,17.000000,6500.000000,1901.134317,825.485459,0.142857,12.000000
max,19043.138560,1.000000,49039.570000,40761.250000,22500.000000,47137.211760,1.000000,1.000000,1.000000,1.500000,123.000000,358.000000,30000.000000,50721.483360,76406.207520,1.000000,12.000000

In [13]:
data.sample(10)

,cust_id,balance,balance_frequency,purchases,oneoff_purchases,installments_purchases,cash_advance,purchases_frequency,oneoff_purchases_frequency,purchases_installments_frequency,cash_advance_frequency,cash_advance_trx,purchases_trx,credit_limit,payments,minimum_payments,prc_full_payment,tenure
6588,C16769,42.286207,1.000000,480.37,0.00,480.37,0.000000,1.000000,0.000000,1.000000,0.000000,0,41,6000.0,326.059256,162.785047,0.833333,12
2329,C12402,7156.345546,1.000000,0.00,0.00,0.00,2506.083985,0.000000,0.000000,0.000000,0.250000,6,0,18000.0,3447.733455,1608.111732,0.000000,12
6921,C17110,114.764518,1.000000,1067.50,850.60,216.90,0.000000,0.700000,0.500000,0.200000,0.000000,0,8,4000.0,577.184902,166.462926,0.300000,10
7124,C17317,311.540000,0.777778,2783.03,2007.26,775.77,0.000000,0.777778,0.777778,0.666667,0.000000,0,32,2000.0,2924.377302,135.530622,1.000000,9
5401,C15554,1719.048074,1.000000,2115.79,1395.05,720.74,0.000000,1.000000,0.583333,0.666667,0.000000,0,34,9000.0,4450.197966,556.179286,0.000000,12
3135,C13225,7387.803893,1.000000,208.00,208.00,0.00,6728.679523,0.250000,0.250000,0.000000,0.416667,7,3,14000.0,1613.637071,1686.828820,0.000000,12
4325,C14445,1068.985549,1.000000,0.00,0.00,0.00,54.671430,0.000000,0.000000,0.000000,0.083333,1,0,1200.0,359.180202,319.230878,0.000000,12
59,C10061,5493.904060,1.000000,229.00,0.00,229.00,970.591332,0.416667,0.000000,0.333333,0.333333,4,6,6000.0,2110.557023,1895.026170,0.000000,12
8218,C18438,1105.179825,1.000000,200.00,200.00,0.00,0.000000,0.083333,0.083333,0.000000,0.000000,0,1,1200.0,308.242594,725.821711,0.000000,12
829,C10860,4270.148411,0.888889,363.00,363.00,0.00,5307.322893,0.111111,0.111111,0.000000,0.555556,11,2,5500.0,1250.695005,2070.907379,0.000000,9

# **Data Cleaning**

**Duplicated Rows**

In [14]:
data[data.duplicated()]

Empty DataFrame
Columns: [cust_id, balance, balance_frequency, purchases, oneoff_purchases, installments_purchases, cash_advance, purchases_frequency, oneoff_purchases_frequency, purchases_installments_frequency, cash_advance_frequency, cash_advance_trx, purchases_trx, credit_limit, payments, minimum_payments, prc_full_payment, tenure]
Index: []

In [15]:
print("Jumlah duplikat : ", data.duplicated().sum())

Jumlah duplikat :  0

**Missing Values**

In [16]:
missing = pd.DataFrame({
    "missing_count": data.isna().sum(),
    "missing_pct": data.isna().mean() * 100
})
display(
    missing.sort_values("missing_pct", ascending=False)
)

                                  missing_count  missing_pct
minimum_payments                            313     3.497207
credit_limit                                  1     0.011173
balance                                       0     0.000000
cust_id                                       0     0.000000
balance_frequency                             0     0.000000
purchases                                     0     0.000000
cash_advance                                  0     0.000000
purchases_frequency                           0     0.000000
oneoff_purchases                              0     0.000000
installments_purchases                        0     0.000000
purchases_installments_frequency              0     0.000000
oneoff_purchases_frequency                    0     0.000000
cash_advance_trx                              0     0.000000
cash_advance_frequency                        0     0.000000
purchases_trx                                 0     0.000000
payments                                      0     0.000000
prc_full_payment                              0     0.000000
tenure                                        0     0.000000

In [17]:
data[data["minimum_payments"].isna()][
    ["balance", "purchases", "cash_advance", "credit_limit", "minimum_payments"]
].describe()

           balance    purchases  cash_advance  credit_limit  minimum_payments
count   313.000000   313.000000    313.000000    313.000000               0.0
mean    555.441321   393.087284    559.136698   3731.789137               NaN
std    1292.687887   757.905701   1185.132567   2924.606153               NaN
min       0.000000     0.000000      0.000000    500.000000               NaN
25%       0.187069     1.400000      0.000000   1500.000000               NaN
50%      16.848358   130.400000      0.000000   3000.000000               NaN
75%     286.686616   399.950000    480.104401   5000.000000               NaN
max    9164.724752  7597.090000   7616.064965  19500.000000               NaN

In [18]:
miss_min_pay = data[data['minimum_payments'].isna()]

total = len(miss_min_pay)
count = len(miss_min_pay[miss_min_pay['balance'] == 0])

print("Jumlah min_payment NaN = ", total)
print("Jumlah min_payment NaN + balance 0 = ",count, "baris")
print(f"Persentase : {count/total:.2%}")

Jumlah min_payment NaN =  313
Jumlah min_payment NaN + balance 0 =  74 baris
Persentase : 23.64%

In [19]:
miss_min_pay.sample(10)

,cust_id,balance,balance_frequency,purchases,oneoff_purchases,installments_purchases,cash_advance,purchases_frequency,oneoff_purchases_frequency,purchases_installments_frequency,cash_advance_frequency,cash_advance_trx,purchases_trx,credit_limit,payments,minimum_payments,prc_full_payment,tenure
6506,C16684,3.647117,0.100000,0.00,0.00,0.00,58.174402,0.000000,0.000000,0.000000,0.100000,2,0,1200.0,0.000000,NaN,0.0,10
920,C10953,39.798993,0.454545,20.09,20.09,0.00,0.000000,0.333333,0.333333,0.000000,0.000000,0,5,3200.0,0.000000,NaN,0.0,12
146,C10152,19.354559,0.909091,689.70,0.00,689.70,0.000000,0.833333,0.000000,0.833333,0.000000,0,10,10000.0,746.691026,NaN,0.0,12
1571,C11624,103.393689,1.000000,0.00,0.00,0.00,1820.800715,0.000000,0.000000,0.000000,0.083333,1,0,3000.0,0.000000,NaN,0.0,12
5828,C15991,323.801713,0.333333,0.00,0.00,0.00,1430.485333,0.000000,0.000000,0.000000,0.166667,1,0,1500.0,0.000000,NaN,0.0,6
8483,C18713,2.433343,0.166667,0.00,0.00,0.00,38.606307,0.000000,0.000000,0.000000,0.166667,1,0,500.0,0.000000,NaN,0.0,6
8198,C18418,247.142072,1.000000,245.00,245.00,0.00,0.000000,0.083333,0.083333,0.000000,0.000000,0,1,500.0,0.000000,NaN,0.0,12
7300,C17497,6.247620,0.272727,108.20,0.00,108.20,0.000000,0.416667,0.000000,0.416667,0.000000,0,5,4500.0,0.000000,NaN,0.0,12
5787,C15949,0.000000,0.000000,102.72,0.00,102.72,0.000000,1.000000,0.000000,1.000000,0.000000,0,12,1500.0,0.000000,NaN,0.0,12
7952,C18167,3.744789,0.090909,78.33,0.00,78.33,0.000000,0.083333,0.000000,0.083333,0.000000,0,1,1000.0,0.000000,NaN,0.0,12

In [20]:
zero_balance_miss = miss_min_pay[miss_min_pay['balance'] == 0]

zero_balance_miss [
    [
        "balance",
        "purchases",
        "cash_advance",
        "payments",
        "purchases_trx",
        "cash_advance_trx",
        "credit_limit",
        "prc_full_payment",
        "tenure"
    ]
].describe().T

,count,mean,std,min,25%,50%,75%,max
balance,74.0,0.000000,0.000000,0.0,0.0000,0.000000,0.000000,0.000000
purchases,74.0,228.079459,271.897249,0.0,54.2125,138.420000,270.990000,1200.000000
cash_advance,74.0,23.315291,76.428228,0.0,0.0000,0.000000,0.000000,465.571691
payments,74.0,548.214303,1891.702817,0.0,0.0000,67.255931,304.430045,14229.882480
purchases_trx,74.0,7.081081,6.172757,0.0,1.2500,6.500000,12.000000,36.000000
cash_advance_trx,74.0,0.121622,0.329079,0.0,0.0000,0.000000,0.000000,1.000000
credit_limit,74.0,3058.108108,1746.072442,500.0,1825.0000,2700.000000,4000.000000,9000.000000
prc_full_payment,74.0,0.000000,0.000000,0.0,0.0000,0.000000,0.000000,0.000000
tenure,74.0,11.594595,1.192659,7.0,12.0000,12.000000,12.000000,12.000000

**Imputasi**

Fill Missing Values -> **minimum_payments**

In [21]:
data.loc[
    (data["balance"] == 0) & (data["minimum_payments"].isna()),
    "minimum_payments"
] = 0

data[data["balance"] == 0].sample(10)

,cust_id,balance,balance_frequency,purchases,oneoff_purchases,installments_purchases,cash_advance,purchases_frequency,oneoff_purchases_frequency,purchases_installments_frequency,cash_advance_frequency,cash_advance_trx,purchases_trx,credit_limit,payments,minimum_payments,prc_full_payment,tenure
5321,C15473,0.0,0.0,54.85,0.00,54.85,0.0,0.333333,0.000000,0.333333,0.0,0,5,5000.0,75.750562,0.0,0.0,12
8023,C18240,0.0,0.0,140.40,0.00,140.40,0.0,1.000000,0.000000,1.000000,0.0,0,12,2200.0,124.992760,0.0,0.0,12
5537,C15693,0.0,0.0,350.48,0.00,350.48,0.0,0.416667,0.000000,0.416667,0.0,0,5,2700.0,681.924724,0.0,0.0,12
3070,C13159,0.0,0.0,63.30,0.00,63.30,0.0,0.250000,0.000000,0.250000,0.0,0,3,2700.0,0.000000,0.0,0.0,12
7257,C17453,0.0,0.0,226.07,0.00,226.07,0.0,0.583333,0.000000,0.583333,0.0,0,7,2500.0,0.000000,0.0,0.0,12
3748,C13855,0.0,0.0,990.00,0.00,990.00,0.0,0.818182,0.000000,0.818182,0.0,0,9,1500.0,0.000000,0.0,0.0,11
7876,C18090,0.0,0.0,420.60,0.00,420.60,0.0,1.000000,0.000000,1.000000,0.0,0,12,2000.0,382.210790,0.0,0.0,12
2178,C12246,0.0,0.0,174.12,0.00,174.12,0.0,1.000000,0.000000,1.000000,0.0,0,12,4000.0,0.000000,0.0,0.0,12
8329,C18550,0.0,0.0,39.54,0.00,39.54,0.0,0.166667,0.000000,0.166667,0.0,0,2,3000.0,181.014541,0.0,0.0,12
3187,C13279,0.0,0.0,61.21,61.21,0.00,0.0,0.083333,0.083333,0.000000,0.0,0,1,2600.0,0.000000,0.0,0.0,12

In [22]:
missing = pd.DataFrame({
    "missing_count": data.isna().sum(),
    "missing_pct": data.isna().mean() * 100
})
display(
    missing.sort_values("missing_pct", ascending=False)
)

                                  missing_count  missing_pct
minimum_payments                            239     2.670391
credit_limit                                  1     0.011173
balance                                       0     0.000000
cust_id                                       0     0.000000
balance_frequency                             0     0.000000
purchases                                     0     0.000000
cash_advance                                  0     0.000000
purchases_frequency                           0     0.000000
oneoff_purchases                              0     0.000000
installments_purchases                        0     0.000000
purchases_installments_frequency              0     0.000000
oneoff_purchases_frequency                    0     0.000000
cash_advance_trx                              0     0.000000
cash_advance_frequency                        0     0.000000
purchases_trx                                 0     0.000000
payments                                      0     0.000000
prc_full_payment                              0     0.000000
tenure                                        0     0.000000

In [23]:
med_min_payment = data["minimum_payments"].median()

data.loc[
     (data["balance"] > 0) & (data["minimum_payments"].isna()),
    "minimum_payments"
] = med_min_payment

data[data["minimum_payments"] == med_min_payment]

,cust_id,balance,balance_frequency,purchases,oneoff_purchases,installments_purchases,cash_advance,purchases_frequency,oneoff_purchases_frequency,purchases_installments_frequency,cash_advance_frequency,cash_advance_trx,purchases_trx,credit_limit,payments,minimum_payments,prc_full_payment,tenure
3,C10004,1666.670542,0.636364,1499.00,1499.00,0.0,205.788017,0.083333,0.083333,0.000000,0.083333,1,1,7500.0,0.000000,308.017569,0.0,12
45,C10047,2242.311686,1.000000,437.00,97.00,340.0,184.648692,0.333333,0.083333,0.333333,0.166667,2,5,2400.0,0.000000,308.017569,0.0,12
47,C10049,3910.111237,1.000000,0.00,0.00,0.0,1980.873201,0.000000,0.000000,0.000000,0.500000,7,0,4200.0,0.000000,308.017569,0.0,12
54,C10056,6.660517,0.636364,310.00,0.00,310.0,0.000000,0.666667,0.000000,0.666667,0.000000,0,8,1000.0,417.016763,308.017569,0.0,12
55,C10057,1311.995984,1.000000,1283.90,1283.90,0.0,0.000000,0.250000,0.250000,0.000000,0.000000,0,6,6000.0,0.000000,308.017569,0.0,12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8919,C19160,14.524779,0.333333,152.00,152.00,0.0,0.000000,0.333333,0.333333,0.000000,0.000000,0,2,1500.0,0.000000,308.017569,0.0,6
8929,C19170,371.527312,0.333333,0.00,0.00,0.0,1465.407927,0.000000,0.000000,0.000000,0.166667,5,0,1500.0,0.000000,308.017569,0.0,6
8935,C19176,183.817004,1.000000,465.90,0.00,465.9,0.000000,1.000000,0.000000,0.833333,0.000000,0,6,1500.0,0.000000,308.017569,0.0,6
8944,C19185,193.571722,0.833333,1012.73,1012.73,0.0,0.000000,0.333333,0.333333,0.000000,0.000000,0,2,4000.0,0.000000,308.017569,0.0,6
8946,C19187,19.183215,1.000000,300.00,0.00,300.0,0.000000,1.000000,0.000000,0.833333,0.000000,0,6,1000.0,275.861322,308.017569,0.0,6

In [24]:
missing = pd.DataFrame({
    "missing_count": data.isna().sum(),
    "missing_pct": data.isna().mean() * 100
})
display(
    missing.sort_values("missing_pct", ascending=False)
)

                                  missing_count  missing_pct
credit_limit                                  1     0.011173
cust_id                                       0     0.000000
balance                                       0     0.000000
balance_frequency                             0     0.000000
oneoff_purchases                              0     0.000000
purchases                                     0     0.000000
cash_advance                                  0     0.000000
purchases_frequency                           0     0.000000
oneoff_purchases_frequency                    0     0.000000
installments_purchases                        0     0.000000
purchases_installments_frequency              0     0.000000
cash_advance_frequency                        0     0.000000
cash_advance_trx                              0     0.000000
purchases_trx                                 0     0.000000
payments                                      0     0.000000
minimum_payments                              0     0.000000
prc_full_payment                              0     0.000000
tenure                                        0     0.000000

Fill Missing Values -> **credit_limit**

In [25]:
data[data["credit_limit"].isna()][["cust_id", "credit_limit"]]

     cust_id  credit_limit
5203  C15349           NaN

In [26]:
med_credit_limit = data["credit_limit"].median()

data.loc[
    (data["credit_limit"].isna()), "credit_limit"
] = med_credit_limit

data[data["cust_id"] == "C15349"][["cust_id","credit_limit"]]

     cust_id  credit_limit
5203  C15349        3000.0

# **Save Dataset**

## Save Dataset Mentah

In [28]:
data.to_csv("../data/raw/customer_data.csv", index=False)

## Save Dataset yang Sudah Bersih

In [29]:
data.to_csv("../data/processed/credit_card_clean.csv", index=False)