# **Import Requirements**

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import pandas as pd
import kagglehub
from kagglehub import KaggleDatasetAdapter
from google.colab import drive

In [ ]:
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

# **Data Acquisition**

In [ ]:
data = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "arjunbhasin2013/ccdata",
  "CC GENERAL.csv",
  )

/tmp/ipykernel_6889/2736278718.py:1: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  data = kagglehub.load_dataset(

Using Colab cache for faster access to the 'ccdata' dataset.

In [ ]:
print("Jumlah baris = ",data.shape[0])
print("Jumlah kolom = ",data.shape[1])

Jumlah baris =  8950
Jumlah kolom =  18

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8950 entries, 0 to 8949
Data columns (total 18 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   CUST_ID                           8950 non-null   object
 1   BALANCE                           8950 non-null   float64
 2   BALANCE_FREQUENCY                 8950 non-null   float64
 3   PURCHASES                         8950 non-null   float64
 4   ONEOFF_PURCHASES                  8950 non-null   float64
 5   INSTALLMENTS_PURCHASES            8950 non-null   float64
 6   CASH_ADVANCE                      8950 non-null   float64
 7   PURCHASES_FREQUENCY               8950 non-null   float64
 8   ONEOFF_PURCHASES_FREQUENCY        8950 non-null   float64
 9   PURCHASES_INSTALLMENTS_FREQUENCY  8950 non-null   float64
 10  CASH_ADVANCE_FREQUENCY            8950 non-null   float64
 11  CASH_ADVANCE_TRX                  8950 non-null   int64
 12  PURCHASES_TRX                     8950 non-null   int64
 13  CREDIT_LIMIT                      8949 non-null   float64
 14  PAYMENTS                          8950 non-null   float64
 15  MINIMUM_PAYMENTS                  8637 non-null   float64
 16  PRC_FULL_PAYMENT                  8950 non-null   float64
 17  TENURE                            8950 non-null   int64
dtypes: float64(14), int64(3), object(1)
memory usage: 1.2+ MB

In [ ]:
data.columns = data.columns.str.lower()
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8950 entries, 0 to 8949
Data columns (total 18 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   cust_id                           8950 non-null   object
 1   balance                           8950 non-null   float64
 2   balance_frequency                 8950 non-null   float64
 3   purchases                         8950 non-null   float64
 4   oneoff_purchases                  8950 non-null   float64
 5   installments_purchases            8950 non-null   float64
 6   cash_advance                      8950 non-null   float64
 7   purchases_frequency               8950 non-null   float64
 8   oneoff_purchases_frequency        8950 non-null   float64
 9   purchases_installments_frequency  8950 non-null   float64
 10  cash_advance_frequency            8950 non-null   float64
 11  cash_advance_trx                  8950 non-null   int64
 12  purchases_trx                     8950 non-null   int64
 13  credit_limit                      8949 non-null   float64
 14  payments                          8950 non-null   float64
 15  minimum_payments                  8637 non-null   float64
 16  prc_full_payment                  8950 non-null   float64
 17  tenure                            8950 non-null   int64
dtypes: float64(14), int64(3), object(1)
memory usage: 1.2+ MB

In [ ]:
data.describe()

,balance,balance_frequency,purchases,oneoff_purchases,installments_purchases,cash_advance,purchases_frequency,oneoff_purchases_frequency,purchases_installments_frequency,cash_advance_frequency,cash_advance_trx,purchases_trx,credit_limit,payments,minimum_payments,prc_full_payment,tenure
count,8950.000000,8950.000000,8950.000000,8950.000000,8950.000000,8950.000000,8950.000000,8950.000000,8950.000000,8950.000000,8950.000000,8950.000000,8949.000000,8950.000000,8637.000000,8950.000000,8950.000000
mean,1564.474828,0.877271,1003.204834,592.437371,411.067645,978.871112,0.490351,0.202458,0.364437,0.135144,3.248827,14.709832,4494.449450,1733.143852,864.206542,0.153715,11.517318
std,2081.531879,0.236904,2136.634782,1659.887917,904.338115,2097.163877,0.401371,0.298336,0.397448,0.200121,6.824647,24.857649,3638.815725,2895.063757,2372.446607,0.292499,1.338331
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,50.000000,0.000000,0.019163,0.000000,6.000000
25%,128.281915,0.888889,39.635000,0.000000,0.000000,0.000000,0.083333,0.000000,0.000000,0.000000,0.000000,1.000000,1600.000000,383.276166,169.123707,0.000000,12.000000
50%,873.385231,1.000000,361.280000,38.000000,89.000000,0.000000,0.500000,0.083333,0.166667,0.000000,0.000000,7.000000,3000.000000,856.901546,312.343947,0.000000,12.000000
75%,2054.140036,1.000000,1110.130000,577.405000,468.637500,1113.821139,0.916667,0.300000,0.750000,0.222222,4.000000,17.000000,6500.000000,1901.134317,825.485459,0.142857,12.000000
max,19043.138560,1.000000,49039.570000,40761.250000,22500.000000,47137.211760,1.000000,1.000000,1.000000,1.500000,123.000000,358.000000,30000.000000,50721.483360,76406.207520,1.000000,12.000000

In [ ]:
data.sample(10)

,cust_id,balance,balance_frequency,purchases,oneoff_purchases,installments_purchases,cash_advance,purchases_frequency,oneoff_purchases_frequency,purchases_installments_frequency,cash_advance_frequency,cash_advance_trx,purchases_trx,credit_limit,payments,minimum_payments,prc_full_payment,tenure
4306,C14425,132.734460,0.1,2190.00,2190.00,0.00,0.000000,0.100000,0.100000,0.000000,0.000000,0,1,2500.0,2.389583,NaN,0.000000,10
8518,C18749,2170.916313,1.0,70.77,70.77,0.00,2524.177008,0.083333,0.083333,0.000000,0.250000,3,1,2500.0,545.076185,470.556714,0.000000,12
7157,C17351,2224.891476,1.0,211.05,211.05,0.00,4014.663620,0.333333,0.333333,0.000000,0.833333,19,4,3000.0,3615.055541,591.521273,0.000000,12
8006,C18223,1256.819270,1.0,1674.96,0.00,1674.96,0.000000,1.000000,0.000000,1.000000,0.000000,0,12,1000.0,970.361646,3449.118706,0.000000,12
7045,C17236,1378.988523,1.0,45.00,45.00,0.00,0.000000,0.500000,0.500000,0.000000,0.000000,0,9,1500.0,326.716166,625.746529,0.000000,12
6367,C16542,2786.817229,1.0,0.00,0.00,0.00,154.876604,0.000000,0.000000,0.000000,0.083333,1,0,7000.0,609.526586,625.852886,0.000000,12
3426,C13523,1243.734425,1.0,0.00,0.00,0.00,306.319900,0.000000,0.000000,0.000000,0.166667,3,0,1500.0,635.639502,342.273932,0.000000,12
682,C10709,2705.591995,1.0,818.02,326.02,492.00,2758.007287,1.000000,0.083333,1.000000,0.083333,3,14,3000.0,4055.341160,1002.627519,0.083333,12
2306,C12377,5897.491823,1.0,0.00,0.00,0.00,3318.487381,0.000000,0.000000,0.000000,0.333333,8,0,7500.0,1417.970244,1809.974326,0.000000,12
5478,C15631,1060.420992,1.0,480.22,295.63,184.59,0.000000,1.000000,0.250000,0.916667,0.000000,0,17,4200.0,2398.956105,342.267500,0.000000,12

# **Data Cleaning**

**Duplicated Rows**

In [ ]:
data[data.duplicated()]

Empty DataFrame
Columns: [cust_id, balance, balance_frequency, purchases, oneoff_purchases, installments_purchases, cash_advance, purchases_frequency, oneoff_purchases_frequency, purchases_installments_frequency, cash_advance_frequency, cash_advance_trx, purchases_trx, credit_limit, payments, minimum_payments, prc_full_payment, tenure]
Index: []

In [ ]:
print("Jumlah duplikat : ", data.duplicated().sum())

Jumlah duplikat :  0

**Missing Values**

In [ ]:
missing = pd.DataFrame({
    "missing_count": data.isna().sum(),
    "missing_pct": data.isna().mean() * 100
})
display(
    missing.sort_values("missing_pct", ascending=False)
)

                                  missing_count  missing_pct
minimum_payments                            313     3.497207
credit_limit                                  1     0.011173
balance                                       0     0.000000
cust_id                                       0     0.000000
balance_frequency                             0     0.000000
purchases                                     0     0.000000
cash_advance                                  0     0.000000
purchases_frequency                           0     0.000000
oneoff_purchases                              0     0.000000
installments_purchases                        0     0.000000
purchases_installments_frequency              0     0.000000
oneoff_purchases_frequency                    0     0.000000
cash_advance_trx                              0     0.000000
cash_advance_frequency                        0     0.000000
purchases_trx                                 0     0.000000
payments                                      0     0.000000
prc_full_payment                              0     0.000000
tenure                                        0     0.000000

In [ ]:
data[data["minimum_payments"].isna()][
    ["balance", "purchases", "cash_advance", "credit_limit", "minimum_payments"]
].describe()

           balance    purchases  cash_advance  credit_limit  minimum_payments
count   313.000000   313.000000    313.000000    313.000000               0.0
mean    555.441321   393.087284    559.136698   3731.789137               NaN
std    1292.687887   757.905701   1185.132567   2924.606153               NaN
min       0.000000     0.000000      0.000000    500.000000               NaN
25%       0.187069     1.400000      0.000000   1500.000000               NaN
50%      16.848358   130.400000      0.000000   3000.000000               NaN
75%     286.686616   399.950000    480.104401   5000.000000               NaN
max    9164.724752  7597.090000   7616.064965  19500.000000               NaN

In [ ]:
miss_min_pay = data[data['minimum_payments'].isna()]

total = len(miss_min_pay)
count = len(miss_min_pay[miss_min_pay['balance'] == 0])

print("Jumlah min_payment NaN = ", total)
print("Jumlah min_payment NaN + balance 0 = ",count, "baris")
print(f"Persentase : {count/total:.2%}")

Jumlah min_payment NaN =  313
Jumlah min_payment NaN + balance 0 =  74 baris
Persentase : 23.64%

In [ ]:
miss_min_pay.sample(10)

,cust_id,balance,balance_frequency,purchases,oneoff_purchases,installments_purchases,cash_advance,purchases_frequency,oneoff_purchases_frequency,purchases_installments_frequency,cash_advance_frequency,cash_advance_trx,purchases_trx,credit_limit,payments,minimum_payments,prc_full_payment,tenure
8519,C18750,11.748193,0.181818,80.75,80.75,0.0,0.000000,0.083333,0.083333,0.000000,0.000000,0,1,2000.0,0.000000,NaN,0.0,12
5228,C15375,138.537976,0.333333,987.45,987.45,0.0,0.000000,0.333333,0.333333,0.000000,0.000000,0,12,3000.0,0.000000,NaN,0.0,6
1188,C11232,6.824905,0.090909,0.00,0.00,0.0,1150.890874,0.000000,0.000000,0.000000,0.083333,1,0,1200.0,0.000000,NaN,0.0,12
3296,C13390,172.316897,0.181818,368.49,368.49,0.0,1731.561995,0.083333,0.083333,0.000000,0.166667,16,2,2500.0,0.000000,NaN,0.0,12
7153,C17347,9.522029,0.272727,458.00,458.00,0.0,0.000000,0.166667,0.166667,0.000000,0.000000,0,2,3000.0,641.866089,NaN,0.0,12
4941,C15080,0.000000,0.000000,0.00,0.00,0.0,253.887233,0.000000,0.000000,0.000000,0.111111,1,0,500.0,2437.932505,NaN,0.0,9
8739,C18977,1367.703777,0.909091,153.00,0.00,153.0,1487.406583,0.545455,0.000000,0.454545,0.090909,14,6,1500.0,0.000000,NaN,0.0,11
8082,C18301,2676.253141,0.909091,0.00,0.00,0.0,2832.570661,0.000000,0.000000,0.000000,0.083333,2,0,3000.0,0.000000,NaN,0.0,12
5219,C15366,6.226972,0.181818,54.00,0.00,54.0,0.000000,0.166667,0.000000,0.083333,0.000000,0,2,3000.0,0.000000,NaN,0.0,12
788,C10817,2302.479845,1.000000,0.00,0.00,0.0,861.574218,0.000000,0.000000,0.000000,0.750000,9,0,2600.0,0.000000,NaN,0.0,12

In [ ]:
zero_balance_miss = miss_min_pay[miss_min_pay['balance'] == 0]

zero_balance_miss [
    [
        "balance",
        "purchases",
        "cash_advance",
        "payments",
        "purchases_trx",
        "cash_advance_trx",
        "credit_limit",
        "prc_full_payment",
        "tenure"
    ]
].describe().T

,count,mean,std,min,25%,50%,75%,max
balance,74.0,0.000000,0.000000,0.0,0.0000,0.000000,0.000000,0.000000
purchases,74.0,228.079459,271.897249,0.0,54.2125,138.420000,270.990000,1200.000000
cash_advance,74.0,23.315291,76.428228,0.0,0.0000,0.000000,0.000000,465.571691
payments,74.0,548.214303,1891.702817,0.0,0.0000,67.255931,304.430045,14229.882480
purchases_trx,74.0,7.081081,6.172757,0.0,1.2500,6.500000,12.000000,36.000000
cash_advance_trx,74.0,0.121622,0.329079,0.0,0.0000,0.000000,0.000000,1.000000
credit_limit,74.0,3058.108108,1746.072442,500.0,1825.0000,2700.000000,4000.000000,9000.000000
prc_full_payment,74.0,0.000000,0.000000,0.0,0.0000,0.000000,0.000000,0.000000
tenure,74.0,11.594595,1.192659,7.0,12.0000,12.000000,12.000000,12.000000

**Imputasi**

Fill Missing Values -> **minimum_payments**

In [ ]:
data.loc[
    (data["balance"] == 0) & (data["minimum_payments"].isna()),
    "minimum_payments"
] = 0

data[data["balance"] == 0].sample(10)

,cust_id,balance,balance_frequency,purchases,oneoff_purchases,installments_purchases,cash_advance,purchases_frequency,oneoff_purchases_frequency,purchases_installments_frequency,cash_advance_frequency,cash_advance_trx,purchases_trx,credit_limit,payments,minimum_payments,prc_full_payment,tenure
5179,C15324,0.0,0.0,933.75,0.0,933.75,0.0,0.750000,0.000000,0.750000,0.0,0,9,4000.0,0.000000,0.000000,0.0,12
6044,C16215,0.0,0.0,240.10,0.0,240.10,0.0,0.583333,0.000000,0.583333,0.0,0,7,2500.0,0.000000,0.000000,0.0,12
1574,C11627,0.0,0.0,2600.00,2600.0,0.00,0.0,0.083333,0.083333,0.000000,0.0,0,1,6000.0,2437.260081,49.283603,0.0,12
1843,C11904,0.0,0.0,369.36,0.0,369.36,0.0,1.000000,0.000000,1.000000,0.0,0,12,1500.0,431.443959,0.000000,0.0,12
5007,C15148,0.0,0.0,66.75,0.0,66.75,0.0,0.250000,0.000000,0.250000,0.0,0,3,4000.0,0.000000,0.000000,0.0,12
8500,C18731,0.0,0.0,113.00,0.0,113.00,0.0,0.333333,0.000000,0.333333,0.0,0,5,4000.0,268.521412,0.000000,0.0,12
8050,C18268,0.0,0.0,271.56,0.0,271.56,0.0,1.000000,0.000000,1.000000,0.0,0,12,2000.0,282.699746,0.000000,0.0,12
8329,C18550,0.0,0.0,39.54,0.0,39.54,0.0,0.166667,0.000000,0.166667,0.0,0,2,3000.0,181.014541,0.000000,0.0,12
7834,C18047,0.0,0.0,1027.92,0.0,1027.92,0.0,1.000000,0.000000,1.000000,0.0,0,12,2500.0,1028.353304,13.395434,0.0,12
7778,C17990,0.0,0.0,147.00,0.0,147.00,0.0,1.000000,0.000000,1.000000,0.0,0,12,2500.0,152.109132,0.000000,0.0,12

In [ ]:
missing = pd.DataFrame({
    "missing_count": data.isna().sum(),
    "missing_pct": data.isna().mean() * 100
})
display(
    missing.sort_values("missing_pct", ascending=False)
)

                                  missing_count  missing_pct
minimum_payments                            239     2.670391
credit_limit                                  1     0.011173
balance                                       0     0.000000
cust_id                                       0     0.000000
balance_frequency                             0     0.000000
purchases                                     0     0.000000
cash_advance                                  0     0.000000
purchases_frequency                           0     0.000000
oneoff_purchases                              0     0.000000
installments_purchases                        0     0.000000
purchases_installments_frequency              0     0.000000
oneoff_purchases_frequency                    0     0.000000
cash_advance_trx                              0     0.000000
cash_advance_frequency                        0     0.000000
purchases_trx                                 0     0.000000
payments                                      0     0.000000
prc_full_payment                              0     0.000000
tenure                                        0     0.000000

In [ ]:
med_min_payment = data["minimum_payments"].median()

data.loc[
     (data["balance"] > 0) & (data["minimum_payments"].isna()),
    "minimum_payments"
] = med_min_payment

data[data["minimum_payments"] == med_min_payment]

,cust_id,balance,balance_frequency,purchases,oneoff_purchases,installments_purchases,cash_advance,purchases_frequency,oneoff_purchases_frequency,purchases_installments_frequency,cash_advance_frequency,cash_advance_trx,purchases_trx,credit_limit,payments,minimum_payments,prc_full_payment,tenure
3,C10004,1666.670542,0.636364,1499.00,1499.00,0.0,205.788017,0.083333,0.083333,0.000000,0.083333,1,1,7500.0,0.000000,308.017569,0.0,12
45,C10047,2242.311686,1.000000,437.00,97.00,340.0,184.648692,0.333333,0.083333,0.333333,0.166667,2,5,2400.0,0.000000,308.017569,0.0,12
47,C10049,3910.111237,1.000000,0.00,0.00,0.0,1980.873201,0.000000,0.000000,0.000000,0.500000,7,0,4200.0,0.000000,308.017569,0.0,12
54,C10056,6.660517,0.636364,310.00,0.00,310.0,0.000000,0.666667,0.000000,0.666667,0.000000,0,8,1000.0,417.016763,308.017569,0.0,12
55,C10057,1311.995984,1.000000,1283.90,1283.90,0.0,0.000000,0.250000,0.250000,0.000000,0.000000,0,6,6000.0,0.000000,308.017569,0.0,12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8919,C19160,14.524779,0.333333,152.00,152.00,0.0,0.000000,0.333333,0.333333,0.000000,0.000000,0,2,1500.0,0.000000,308.017569,0.0,6
8929,C19170,371.527312,0.333333,0.00,0.00,0.0,1465.407927,0.000000,0.000000,0.000000,0.166667,5,0,1500.0,0.000000,308.017569,0.0,6
8935,C19176,183.817004,1.000000,465.90,0.00,465.9,0.000000,1.000000,0.000000,0.833333,0.000000,0,6,1500.0,0.000000,308.017569,0.0,6
8944,C19185,193.571722,0.833333,1012.73,1012.73,0.0,0.000000,0.333333,0.333333,0.000000,0.000000,0,2,4000.0,0.000000,308.017569,0.0,6
8946,C19187,19.183215,1.000000,300.00,0.00,300.0,0.000000,1.000000,0.000000,0.833333,0.000000,0,6,1000.0,275.861322,308.017569,0.0,6

In [ ]:
missing = pd.DataFrame({
    "missing_count": data.isna().sum(),
    "missing_pct": data.isna().mean() * 100
})
display(
    missing.sort_values("missing_pct", ascending=False)
)

                                  missing_count  missing_pct
credit_limit                                  1     0.011173
cust_id                                       0     0.000000
balance                                       0     0.000000
balance_frequency                             0     0.000000
oneoff_purchases                              0     0.000000
purchases                                     0     0.000000
cash_advance                                  0     0.000000
purchases_frequency                           0     0.000000
oneoff_purchases_frequency                    0     0.000000
installments_purchases                        0     0.000000
purchases_installments_frequency              0     0.000000
cash_advance_frequency                        0     0.000000
cash_advance_trx                              0     0.000000
purchases_trx                                 0     0.000000
payments                                      0     0.000000
minimum_payments                              0     0.000000
prc_full_payment                              0     0.000000
tenure                                        0     0.000000

Fill Missing Values -> **credit_limit**

In [ ]:
data[data["credit_limit"].isna()][["cust_id", "credit_limit"]]

     cust_id  credit_limit
5203  C15349           NaN

In [ ]:
med_credit_limit = data["credit_limit"].median()

data.loc[
    (data["credit_limit"].isna()), "credit_limit"
] = med_credit_limit

data[data["cust_id"] == "C15349"][["cust_id","credit_limit"]]

     cust_id  credit_limit
5203  C15349        3000.0

Save Dataset yang Sudah Bersih

In [ ]:
data.to_csv("/content/drive/MyDrive/Credit Card Segmentation/Dataset/Processed/credit_card_clean.csv", index=False)